### ISSUE TITLE
When reproducing on collab, facing issue with the scene_graph file

### ISSUE THREAD

**Issue by kxusx** [liuhengyue/fcsgg#13]
ERROR FACED  : 
No. of images available: 43728. Please download the dataset following the instructions.
Traceback (most recent call last):
  File "/content/fcsgg/tools/train_net.py", line 43, in <module>
    from fcsgg.config import add_fcsgg_config
  File "/content/fcsgg/fcsgg/__init__.py", line 1, in <module>
    from .modeling import meta_arch
  File "/content/fcsgg/fcsgg/modeling/__init__.py", line 1, in <module>
    from .meta_arch import CenterNet
  File "/content/fcsgg/fcsgg/modeling/meta_arch/__init__.py", line 1, in <module>
    from .onestage_detector import CenterNet
  File "/content/fcsgg/fcsgg/modeling/meta_arch/onestage_detector.py", line 35, in <module>
    from fcsgg.data.detection_utils import GroundTruthGen
  File "/content/fcsgg/fcsgg/data/__init__.py", line 2, in <module>
    from . import datasets
  File "/content/fcsgg/fcsgg/data/datasets/__init__.py", line 2, in <module>
    from .visual_genome import register_visual_genome
  File "/content/fcsgg/fcsgg/data/datasets/visual_genome.py", line 500, in <module>
    register_visual_genome()
  File "/content/fcsgg/fcsgg/data/datasets/visual_genome.py", line 494, in register_visual_genome
    predicate_stats=vg_parser.get_predicate_stats(),
  File "/content/fcsgg/fcsgg/data/datasets/visual_genome.py", line 365, in get_predicate_stats
    roi_h5 = h5py.File(self.roidb_file, 'r')
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 9437184, sblock->base_addr = 0, stored_eof = 150724042)

I re-downloaded the h5 file and tried again still same issue. might be corrupted

**Comment by liuhengyue** [comment]
I saw your assertion failed as "No. of images available: 43728. Please download the dataset following the instructions." It seems that you have some images but not all. The file is not liked to be corrupted as it works on my end. 

1. check if you have the correct path and the whole dataset; 2. try an old environment 'cause I see you are using Python 3.10, maybe use older versions of python, pytorch, h5py, etc.
